/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interF;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import library.management.system.DBconnect;

/**
 *
 * @author tharukshi
 * 
 */
public class Book_details extends javax.swing.JInternalFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Book_details
     */
    public Book_details() {
        initComponents();
        
        //connect to DATABASE
        con = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookIDbox = new javax.swing.JLabel();
        BookNamebox = new javax.swing.JLabel();
        AutherNamebox = new javax.swing.JLabel();
        Isbnbox = new javax.swing.JLabel();
        lengthbox = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bookIdbox = new javax.swing.JComboBox<>();
        bookNamebox = new javax.swing.JTextField();
        autherNamebox = new javax.swing.JTextField();
        ISBNbox = new javax.swing.JTextField();
        Lengthbox = new javax.swing.JTextField();

        bookIDbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookIDbox.setText("Book ID");

        BookNamebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BookNamebox.setText("Book name");

        AutherNamebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AutherNamebox.setText("Auther name");

        Isbnbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Isbnbox.setText("ISBN");

        lengthbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lengthbox.setText("Length");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bookIdbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookIdbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book ID Number", "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012", "013", "014", "015", "016", "017", "018", "019", "020", "021", "022", "023", "024", "025", "026", "027", "028", "029", "030", "031", "032", "033", "034", "035", "036", "037", "038", "039", "040", "041", "042", "043", "044", "045", "046", "047", "048", "049", "050" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookIDbox)
                            .addComponent(BookNamebox)
                            .addComponent(AutherNamebox)
                            .addComponent(Isbnbox)
                            .addComponent(lengthbox))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookIdbox, 0, 150, Short.MAX_VALUE)
                            .addComponent(bookNamebox)
                            .addComponent(autherNamebox)
                            .addComponent(ISBNbox)
                            .addComponent(Lengthbox))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookIDbox)
                    .addComponent(bookIdbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookNamebox)
                    .addComponent(bookNamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutherNamebox)
                    .addComponent(autherNamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isbnbox)
                    .addComponent(ISBNbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthbox)
                    .addComponent(Lengthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       String bookId = bookIdbox.getSelectedItem().toString();
       String bookName = bookNamebox.getText();
       String autherName = autherNamebox.getText();
       String ISBN = ISBNbox.getText();
       String Length = Lengthbox.getText();
      
       try { 
             String q = "INSERT INTO Book_details (bookId,bookName, autherName,ISBN,Length ("+bookId+"','"+bookName+"','"+autherName+"','" +ISBN+"','"+ Length+"')";
              pst =  con.prepareStatement(q);
              pst.execute(q);
              JOptionPane.showMessageDialog(null, "New BOOK Added!");
              rs.close();
              pst.close();
       
            
       } catch (Exception e) {
                 
       }
         
            
                
                
                
                
                
                
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutherNamebox;
    private javax.swing.JLabel BookNamebox;
    private javax.swing.JTextField ISBNbox;
    private javax.swing.JLabel Isbnbox;
    private javax.swing.JTextField Lengthbox;
    private javax.swing.JTextField autherNamebox;
    private javax.swing.JLabel bookIDbox;
    private javax.swing.JComboBox<String> bookIdbox;
    private javax.swing.JTextField bookNamebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lengthbox;
    // End of variables declaration//GEN-END:variables

    private static class Exeption {

        public Exeption() {
        }
    }
}
