/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interF;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.jar.Attributes.Name;
import library.management.system.DBconnect;

/**
 *
 * @author Kumudini
 */
public class DVD_details extends javax.swing.JInternalFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form DVD_details
     */
    public DVD_details() {
        initComponents();
        
        //connect to DATABASE
        
        con = DBconnect.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JLabel();
        movie = new javax.swing.JLabel();
        director = new javax.swing.JLabel();
        studio = new javax.swing.JLabel();
        ST = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dvdidbox = new javax.swing.JComboBox<>();
        movienamebox = new javax.swing.JTextField();
        directornamebox = new javax.swing.JTextField();
        makerstudiobox = new javax.swing.JTextField();
        subtitlebox = new javax.swing.JTextField();

        Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Id.setText("DVD ID");

        movie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movie.setText("Movie Name");

        director.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        director.setText("Director Name");

        studio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studio.setText("Maker Studio");

        ST.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ST.setText("Subtitle");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dvdidbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD ID Number", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id)
                    .addComponent(movie)
                    .addComponent(ST)
                    .addComponent(studio)
                    .addComponent(director))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(makerstudiobox)
                    .addComponent(subtitlebox, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dvdidbox, 0, 135, Short.MAX_VALUE)
                        .addComponent(movienamebox)
                        .addComponent(directornamebox)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id)
                    .addComponent(dvdidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movie)
                    .addComponent(movienamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(director)
                    .addComponent(directornamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studio)
                    .addComponent(makerstudiobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ST)
                    .addComponent(subtitlebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String dvdid = dvdidbox.getSelectedItem().toString();
        String moviename = movienamebox.getText();
        String directorname = directornamebox.getText();
        String makerstudio = makerstudiobox.getText();
        String subtitle = subtitlebox.getText();
        
        try {
       String q = "INSERT INTO DVD_details (dvdid,moviename,directorname,makerstudio,subtitle) values ('"+dvdid+"','"+moviename+"','"+directorname+"','"+makerstudio+"','"+subtitle+"')";
        pst = con.prepareStatement(q);
        pst.execute();
        } catch (Exception e) {
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JLabel ST;
    private javax.swing.JLabel director;
    private javax.swing.JTextField directornamebox;
    private javax.swing.JComboBox<String> dvdidbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField makerstudiobox;
    private javax.swing.JLabel movie;
    private javax.swing.JTextField movienamebox;
    private javax.swing.JLabel studio;
    private javax.swing.JTextField subtitlebox;
    // End of variables declaration//GEN-END:variables

    private Object movienamebox() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
